### PR TITLE
Update REDAEDME.rst

### PR DESCRIPTION
**Pull request by BCNelson**
The original didn't work for me this change did.

### CODE REVIEW

**Comment by Fleker** [comment]
We should probably update the README, although the proposed change is probably not the ideal solution. It should mirror the content in the docs for [Download the Library and Run the Sample](https://developers.google.com/assistant/sdk/develop/python/run-sample)

**Comment by BCNelson** [comment]
I signed it!

**Comment by BCNelson** [comment]
The Problem is the page [Download the Library and Run the Sample](https://developers.google.com/assistant/sdk/develop/python/run-sample) is not correct either and no other resources I could find listed that command I had to go in the source code to find the correct command. Did I just miss it in the other places or is it not there

**Comment by Fleker** [comment]
I'll try to confirm this tomorrow. But I'm pretty sure there's some documentation somewhere on the right set of commands even if the specific README is not.

**Comment by proppy** [comment]
@BCNelson can you confirm that the following command don't work for you:
```
tmp 👺  python3 -m venv env
tmp 🍊  env/bin/pip install --upgrade google-auth-oauthlib[tool]
Requirement already up-to-date: google-auth-oauthlib[tool] in ./env/lib/python3.4/site-packages
  Installing extra requirements: 'tool'
Cleaning up...
tmp 🍊  env/bin/google-oauthlib-tool
Usage: google-oauthlib-tool [OPTIONS]

Error: Missing option "--client-secrets".
tmp 👺
```

They work for me in a fresh virtualenv.

**Pull request closed without merging**
